### ISSUE TITLE
desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [1000ch/quail#5]
desktop file does not pass `desktop-file-validate`:

```
quail.desktop: error: value "Productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Productivity"; values extending the format should start with "X-"
/tmp/.mount_BeingTSZfJcP/quail.desktop: hint: value "Productivity;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2189

**Comment by probonopd** [comment]
Same for Whale.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2190

**Comment by 1000ch** [comment]
@probonopd Could you try it again with [`v2.0.1`](https://github.com/1000ch/quail/releases/tag/v2.0.1)?

**Comment by probonopd** [comment]
Thanks @1000ch. Is there a reason that the architecture is missing in the filename?

**Comment by probonopd** [comment]
Running into another issue now:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/run/firejail/appimage/.appimage-9207/resources/app.asar/node_modules/write-file-atomic/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:327:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:685:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9207/resources/app.asar/node_modules/conf/index.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
0x400003 "quail": ("quail" "Quail")  200x200+0+0  +0+0
0x400001 "quail": ("quail" "Quail")  10x10+10+10  +10+10
NUMBER_OF_WINDOWS: 2
IceWM: using /home/travis/.icewm for private configuration files
convert: unable to read X window image `0x800011': Resource temporarily unavailable @ error/xwindow.c/XImportImage/5005.
convert: no images defined `database/Quail/screenshot.png' @ error/convert.c/ConvertImageCommand/3210.
```

**Comment by syou6162** [comment]
I've got the same error message on macOS. I'm using v2.0.1.

<img width="411" alt="スクリーンショット 2020-10-02 10 28 05" src="https://user-images.githubusercontent.com/18356/94879055-1ba1df00-049a-11eb-9f90-1ddb734489d2.png">

**Comment by 1000ch** [comment]
The problem (mentioned on https://github.com/1000ch/quail/issues/5#issuecomment-699632415) is now solved from [`v2.0.2`](https://github.com/1000ch/quail/releases/tag/v2.0.2).

**Comment by 1000ch** [comment]
> Is there a reason that the architecture is missing in the filename?

@probonopd I'm still wondering what is the problem you mentioned. Could you explain it a little bit more?

**Comment by syou6162** [comment]
@1000ch I downloaded latest version v2.0.2, and I confirmed this issue has been resolved. Thakn you!

**Comment by probonopd** [comment]
> @probonopd I'm still wondering what is the problem you mentioned. Could you explain it a little bit more?

Is there a reason the file is not called `Quail-2.0.2-x86_64.AppImage` (assuming that the AppImage is for that architecture?)

**Comment by 1000ch** [comment]
The file is distributed by `electron-builder` and automatically named as `Quail-2.0.2.AppImage`. Can I ask why should that filename include the architecture?
